

trigger: none          # in which branch pipeline will run
pool: linux            # on which agent pipeline will run (on single pool we can run multiple agent) 

# Step 1: Install unzip (TerraformInstaller ko ye chahiye hota hai)

steps:
- script: |
    sudo apt-get update -y
    sudo apt-get install unzip -y
  displayName: 'Install unzip utility'
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'ADO-pipeline'
    backendAzureRmOverrideSubscriptionID: '9f14d6da-b117-434d-922f-f763c8ec88bb'
    backendAzureRmResourceGroupName: 'suchita-rg'
    backendAzureRmStorageAccountName: 'suchidevstorage980'
    backendAzureRmContainerName: 'suchidevstoragecontainer980'
    backendAzureRmKey: 'suchi.tfstate'
  displayName: terraform init
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
  displayName: terraform validate 
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'ADO-pipeline'
  displayName: terraform plan 
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'ADO-pipeline'
  displayName: terraform apply

